
require('./assets/migration/use_reversed_rotateBy');
require('./assets/scripts/FlashLightCtrlComponent');
require('./assets/scripts/FlashLightEffectScene');
require('./assets/scripts/GaussianBlurV1EffectScene');
require('./assets/scripts/GlowInnerV1EffectScene');
require('./assets/scripts/GlowInnerV2EffectScene');
require('./assets/scripts/GlowOutterEffectScene');
require('./assets/scripts/GrayEffectScene');
require('./assets/scripts/LoadingStyleEffect1Scene');
require('./assets/scripts/MosaicEffectScene');
require('./assets/scripts/OldPhotoEffectScene');
require('./assets/scripts/OutlineEffectScene');
require('./assets/scripts/PointLightCtrlComponent');
require('./assets/scripts/PointLightEffectScene');
require('./assets/scripts/PreviewEffectScene');
require('./assets/scripts/RoundCornerCropV1EffectScene');
require('./assets/scripts/RoundCornerCropV2EffectScene');
require('./assets/scripts/ccutils/multiresolution/ContentAdapter');
